import Navbar from "@/components/navbar";
import { type Metadata } from "next";
import { Alegreya_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Gempire",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const alegreya = Alegreya_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export default function StoreLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <body className={`${alegreya.className} mx-auto max-w-7xl`}>
        <Navbar />
        {children}
      </body>
    </>
  );
}
