import "@/styles/globals.css";

import { type Metadata } from "next";
import { Poppins, Raleway } from "next/font/google";
import { QueryProvider } from "./utils/query-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

// const geist = Geist({
//   subsets: ["latin"],
//   variable: "--font-geist-sans",
// });

// const jakarta = Plus_Jakarta_Sans({
//   subsets: ["latin"],
//   variable: "--font-jakarta-sans",
// });

// const lora = Lora({
//   subsets: ["latin"],
//   variable: "--font-lora",
// });

// const roboto = Roboto_Mono({
//   subsets: ["latin"],
//   variable: "--font-roboto-mono",
// });

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500"],
  variable: "--display-family",
});

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--text-family",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <QueryProvider>
      <html
        lang="en"
        // className={`${jakarta.variable} ${lora.variable} ${roboto.variable}`}
        className={`${poppins.variable} ${raleway.variable}`}
        suppressHydrationWarning
      >
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </QueryProvider>
  );
}
